version: "3.6"

services:
  goligoli_be:
    image: php:7-alpine
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    environment:
      docker: "true"
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
#          resources:
#            limits:
#              cpus: "0.1"
#              memory: 50M
      restart_policy:
        condition: on-failure
    ports:
    - 8080:8080
    depends_on:
    - mysql
    volumes:
    - .:/var/www
    - logs:/var/www/logs
    networks:
    - net

  mysql:
    image: mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
    - 3306:3306
    volumes:
    - mysql_data:/var/lib/mysql
    networks:
    - net

  redis:
    image: redis:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
    - net

volumes:
  logs:
  mysql_data:

networks:
  net:
